FROM golang
ADD . /go/src/github.com/amlana21/grpc-aws
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main ./src/client

EXPOSE 5301
EXPOSE 50052
CMD ["/app/main"] 